In [3]:
!pip install pandas

188.16s - pydevd: Sending message related to process being replaced timed-out after 5 seconds


  Using cached pandas-3.0.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 62.2 MB/s  0:00:00s eta 0:00:01

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python3 -m pip install --upgrade pip


In [4]:
import pandas as pd

In [6]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv')

In [7]:
df.head

<bound method NDFrame.head of                                                  Laptop       Status   Brand  \
0     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...          New    Asus   
1     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          New  Alurin   
2     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...          New    Asus   
3     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New     MSI   
4     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...          New      HP   
...                                                 ...          ...     ...   
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished   Razer   
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished   Razer   

         

In [1]:
import numpy as np

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.ones(4)

array([1., 1., 1., 1.])

In [7]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [9]:
a = np.array([1,2,3,4])

In [10]:
a

array([1, 2, 3, 4])

In [11]:
a[2] = 5

In [12]:
a

array([1, 2, 5, 4])

In [13]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [14]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [16]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
n = np.array([
    [1,2,3],
    [4,5,6]
])

In [21]:
n[0, 2] = 30

In [22]:
n

array([[ 1,  2, 30],
       [ 4,  5,  6]])

In [23]:
n[:,2]

array([30,  6])

In [24]:
n[0,:]

array([ 1,  2, 30])

In [27]:
np.random.seed(10)
np.random.rand(5,2)

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665],
       [0.19806286, 0.76053071],
       [0.16911084, 0.08833981]])

In [29]:
np.random.randn(5,2)

array([[-1.13660221,  0.13513688],
       [ 1.484537  , -1.07980489],
       [-1.97772828, -1.7433723 ],
       [ 0.26607016,  2.38496733],
       [ 1.12369125,  1.67262221]])

In [30]:
np.random.randint(low=0, high=5, size=(3,2))

array([[0, 3],
       [4, 2],
       [0, 1]])

In [34]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [35]:
b = 10 + (a * 5)

In [36]:
b

array([10, 15, 20, 25])

In [37]:
a + b

array([10, 16, 22, 28])

In [38]:
a >= 2

array([False, False,  True,  True])

In [39]:
a.sum()

np.int64(6)

In [40]:
a.min()

np.int64(0)

In [41]:
a.mean()

np.float64(1.5)

In [42]:
a.std()

np.float64(1.118033988749895)